version: 2.1
executors:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/SMOLKEYS/yellow-java/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:

    executor: build
    steps:
      - checkout
      - run: |
          ls

workflows:
  my-custom-workflow:
    jobs:
      - build