name: Decompiled Sources CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17
      - name: Use different metadata
        run: |
          rm mod.hjson
          printf 'name: "yellow-java"\ndisplayName: "Yellow BE (Java)"\nsubtitle: "BE Build ${{ github.run_number }}"\nversion: ${{ github.run_number }}\nminGameVersion: 138\nmain: "yellow.Yellow"' >> mod.hjson
      - name: Build mod jar
        run: chmod +x ./gradlew; ./gradlew deploy -Duse-k2
      - name: Move jar to root
        run: mv build/libs/yellow-java.jar .
      - name: Get the Procyon decompiler AND get the decomp sources repo
        run: 'wget https://github.com/mstrobel/procyon/releases/download/v0.6.0/procyon-decompiler-0.6.0.jar && git clone https://github.com/SMOLKEYS/yellow-java-sources'
      - name: Decompile the mod and dump to the sources folder
        run: 'java -jar procyon-decompiler-0.6.0.jar yellow-java.jar -o yellow-java-sources -ec -ps -ss'
      - name: Push to repo
        run: |
          cd yellow-java-sources
          git config --global user.name "Github CLI"
          git config --global user.email "cli@github.com"
          git add .
          git commit -m "sources-update"
          git push https://SMOLKEYS:${{ secrets.GTOKEN }}@github.com/SMOLKEYS/yellow-java-sources
          cd ../
